### ISSUE TITLE
Active Game Logging | Formatting Algorithm Implementation

### ISSUE THREAD

**Issue by jasonmzx** [jasonmzx/Black-Jack-Replay-3700U#2]
![image](https://github.com/jasonmzx/Black-Jack-Replay-3700U/assets/68576119/47d78c8d-73aa-40fe-a73f-1e7206247451)

I've implemented the functional & rendering portion of the game log, but the actual strings that are generated as "logs" are still choppy

In `src/util/browserUtil.js`

[BrowserUtil.js full source code](https://github.com/jasonmzx/Black-Jack-Replay-3700U/blob/main/Frontend/blackjack-web/src/util/browserUtil.js)

```javascript
export function activeGameLoggingAlgorithm(state, hands) {

    let lg = [];

    for(const [idx,hand] of hands.entries()) {
        lg.push(
            <>
                {hand["holder"] ? "Dealer" : "Player"} drew a {hand["card_name"]} of {hand["symbol_name"]} | VALUE: {hand["card_value"]}
            </>
        );
    }

    return lg;
}
```

Here you can see I'm doing a very lazy format, I want you to go in and improve this algorithm, for the Parameter inputs, keep those the same, **state** refers to general game state, 0: player's turn, 1: dealer's turn, 1< someone won or lost...

and a sample of the **hands** object follows:

```json
[
    {
      "card_id": 33,
      "shown": 1,
      "holder": 0,
      "symbol_type": 3,
      "symbol_name": "Spades",
      "card_type": 0,
      "card_value": 7,
      "card_name": ""
    },
    {
      "card_id": 9,
      "shown": 1,
      "holder": 0,
      "symbol_type": 0,
      "symbol_name": "Clubs",
      "card_type": 0,
      "card_value": 10,
      "card_name": ""
    },
    {
      "card_id": 29,
      "shown": 1,
      "holder": 1,
      "symbol_type": 3,
      "symbol_name": "Spades",
      "card_type": 0,
      "card_value": 3,
      "card_name": ""
    },
    {
      "card_id": -1,
      "shown": 0,
      "holder": 1,
      "symbol_type": -1,
      "symbol_name": "",
      "card_type": -1,
      "card_value": -1,
      "card_name": ""
    },
    {
      "card_id": 32,
      "shown": 1,
      "holder": 0,
      "symbol_type": 3,
      "symbol_name": "Spades",
      "card_type": 0,
      "card_value": 6,
      "card_name": ""
    }
  ]
```

**Comment by tahmid-chowdhury** [comment]
![image](https://github.com/jasonmzx/Black-Jack-Replay-3700U/assets/32552650/d7c04768-819f-455f-bab0-f3e09d27817e)

The logs look a little nicer now, but I'm having a little trouble with showing each person's visible cards and their total value after each turn.

```js
export function activeGameLoggingAlgorithm(state, hands) {
    let lg = []

    for(const [idx,hand] of hands.entries()) {
        if (hand.shown) {
            const playerName = hand.holder === 0 ? "Player" : "Dealer"

            const cardDescription = `${getCardDescription(hand)}`
            const visibleCards = getVisibleCards(hands, hand.holder).map(card => getCardDescription(card)).join(", ")
            const totalValue = calculateTotalValue(hands, hand.holder)

            lg.push(
                `${playerName} drew ${cardDescription}`
                /* | ${playerName} cards: ${visibleCards} | Total value: ${totalValue} */
            )
        }
    }

    return lg
}
```

This is how `activeGameLoggingAlgorithm()` looks as of right now. A part of the `lg.push()` has been commented out for the time being, this is the part that's been giving me issues (I'll get to this later in this post).

In addition to improving `activeGameLoggingAlgorithm()`, I have added three new functions as follows:

```js
function getCardDescription(card) {
    return card.card_name ? `${card.card_name} of ${card.symbol_name} (Value: ${card.card_value})` : `${card.card_value} of ${card.symbol_name} (Value: ${card.card_value})`
}
```

`getCardDescription()`: Checks for face values and returns a description of the card accordingly

```js
function calculateTotalValue(hands, holder) {
    const playerCards = getVisibleCards(hands, holder)
    return playerCards.reduce((total, card) => total + card.card_value, 0)
}
```

`calculateTotalValue()`: Checks the player's visible cards and returns a total integer value for their hand

```js
function getVisibleCards(hands, holder) {
    return hands.filter((hand) => hand.holder === holder && hand.shown)
}
```

`getVisibleCards()`: Checks the player's hand for visible cards and returns them

![image](https://github.com/jasonmzx/Black-Jack-Replay-3700U/assets/32552650/ace69742-4e5b-4454-9a88-98cb580f2840)

As we can see here, attempting to show the player's visible cards after each step instead lists all the player's visible cards at the present game state instead of incrementally (not sure if that's the right term). We can also see a similar issue with the hand's total value, as the present total is shown instead of the total after each step.

What's done in my commit that follows this post:
* The game log strings are easier to read and understand
* The `activeGameLoggingAlgorithm()` has been improved slightly
* `getCardDescription()`, `calculateTotalValue()`, and `getVisibleCards()` have been added

What's left to do:
* Small error with Ace not showing the correct value ("null" instead of "1" or "11")
* Show visible cards incrementally, after each step (I'm thinking of solving this issue using an array)
* Show total value incrementally, after each step (once again, I believe an array may be useful to solve this issue)

**Comment by jasonmzx** [comment]
Ok, Please also show in the log, that the Dealer drew an unknown card instead of omitting it

**Comment by tahmid-chowdhury** [comment]
![image](https://github.com/jasonmzx/Black-Jack-Replay-3700U/assets/32552650/48d8d64b-8833-42da-887e-2dd14a507dea)

I added a simple else statement to the algorithm to mention that an unknown card was drawn if the card drawn is not shown.

**Comment by tahmid-chowdhury** [comment]
![image](https://github.com/jasonmzx/Black-Jack-Replay-3700U/assets/32552650/a0d49941-1d27-4399-848e-bb43b39c5c69)

The log is essentially complete now, the issue with the visible cards and total value has been solved.

The following is the most up to date code, with the fixes I've implemented:
```js
export function activeGameLoggingAlgorithm(state, hands) {
    let lg = []

    for(const [idx,hand] of hands.entries()) {
        if (hand.shown) {
            const playerName = hand.holder === 0 ? "Player" : "Dealer"

            const cardDescription = getCardDescription(hand)
            const visibleCards = getVisibleCards(hands, hand.holder, idx).map(card => getCardDescription(card)).join(", ")
            const totalValue = calculateTotalValue(hands, hand.holder, idx)

            lg.push(
                `${playerName} drew ${cardDescription} (Value: ${hand.card_value}) | ${playerName} cards: ${visibleCards} | Total value: ${totalValue}`
            )
        } else {
            lg.push(`Dealer drew an unknown card`)
        }
    }

    return lg
}

function getCardDescription(card) {
    return card.card_name ? `${card.card_name} of ${card.symbol_name}` : `${card.card_value} of ${card.symbol_name}`
}

function calculateTotalValue(hands, holder, idx) {
    const playerCards = getVisibleCards(hands, holder, idx).slice(0, idx + 1)
    return playerCards.reduce((total, card) => total + card.card_value, 0)
}

function getVisibleCards(hands, holder, idx) {
    return hands.slice(0, idx + 1).filter((hand) => hand.holder === holder && hand.shown)
}
```

All that's left to complete at this point, I believe, is the issue with Ace cards showing "null" instead of "1" or "11". If I've missed anything or there are any suggestions, feel free to mention them.

**Comment by tahmid-chowdhury** [comment]
![image](https://github.com/jasonmzx/Black-Jack-Replay-3700U/assets/32552650/525d61cf-8bc0-4629-a865-341e67f022f4)

The issue with Ace cards showing incorrectly has been resolved, as far as I can tell. The following changes were made to the code:

```js
let cardValue
            if (hand.card_value === null && (totalValue - 11) <= 10) {
                cardValue = "11"
            } else if (hand.card_value === null && (totalValue - 11) > 10) {
                cardValue = "1"
            } else {
                cardValue = hand.card_value
            }
```
Here, in an updated version of `activeGameLoggingAlgorithm()` we use `cardValue` to determine which value to assign to the Ace card when it is drawn, and its value is printed.

```js
function calculateTotalValue(hands, holder, idx) {
    const playerCards = getVisibleCards(hands, holder, idx).slice(0, idx + 1)
    let total = 0
    let hasAce = false

    for(const card of playerCards) {
        if (card.card_value === null) {
            total += 11
            hasAce = true
        }

        total += card.card_value
    }

    if (total > 21 && hasAce) {
        total -= 10
    }

    return total
}
```

Here, we see that the `calculateTotalValue()` function has been updated to accommodate Ace cards and add them correctly to the total value of a hand.

Based on these improvements and additions, I'm closing the issue here. If any bugs or errors are discovered, however, I may have to reopen it to make a few adjustments.
